# Generated by Django 4.0.3 on 2022-04-05 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='todoinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='タスク詳細')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='期限')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
        ),
    ]
