# Generated by Django 4.0.3 on 2022-03-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, verbose_name='ユーザーID')),
                ('password', models.CharField(max_length=30, verbose_name='パスワード')),
                ('username', models.CharField(max_length=30, verbose_name='ユーザー名')),
            ],
        ),
        migrations.CreateModel(
            name='todoinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, verbose_name='タスク詳細')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='期限')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApp.userinf', verbose_name='ユーザーID')),
            ],
        ),
    ]
