# Generated by Django 4.0.3 on 2022-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('updated', models.CharField(max_length=8)),
                ('deadline', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Userinf',
        ),
    ]
