# Generated by Django 4.0.3 on 2022-03-27 10:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_todoinf_delete_userinf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoinf',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 10, 10, 16, 127802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoinf',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todoinf',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
