# Generated by Django 4.0.3 on 2022-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_todoinf_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoinf',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='タスク詳細'),
        ),
    ]
