# Generated by Django 4.0.3 on 2022-03-28 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0006_alter_todoinf_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoinf',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 28, 17, 46, 25, 709895, tzinfo=utc)),
        ),
    ]
